(clear)
(load "ontologia.clp")
(load "instancies_ciutat.clp")
(load instancies_solicitants.clp)
(load "abstraccio.clp")
(load "resolucio.clp")
(load "refinament.clp")
(load "main.clp")
(reset)
(main)
